In [18]:
!pip install numpy

# Creating arrays

In [24]:
# Creating
import numpy as np
a = np.zeros(3) 
a
type(a)
type(a[0])

numpy.float64

In [26]:
a.shape

(3,)

In [29]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
type(z[0])

numpy.float64

In [31]:
z = np.empty(3)
z

array([0., 0., 0.])

In [33]:
z = np.linspace(2,10,5) # From 2 to 10, with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [34]:
z = np.array([10,20]) # ndsarray from python list
z

array([10, 20])

In [36]:
alist = [10,20,30,40,50]
z = np.array([alist])
z

array([10, 20, 30, 40, 50])

In [37]:
type(z)

numpy.ndarray

## 2D Array

In [52]:
b_list = [[8,9,0,4,5,6],[67,35,677,79, 67,78]] # 2d array
z = np.array([b_list])
z

array([[[  8,   9,   0,   4,   5,   6],
        [ 67,  35, 677,  79,  67,  78]]])

In [46]:
type(z)

numpy.ndarray

In [54]:
z.shape

(1, 2, 6)

## Random Array
